### ISSUE TITLE
How to set min_refresh_interval to 1s/500ms in Azure Managed Grafana

### ISSUE THREAD

**Issue by rolandkru** [anshulsharmas/F1_ADX#1]
Hi Anshul

Thank you very much for sharing. I adapted you project to .NET 6 for the edge micro service, F1 2020 (since F1 2019 didn't start on steam on my Windows 11 PC) and tried to use azure managed grafana. 

However, I don't see a way to set the min_refresh_interval environment variable in azure managed grafana. I know, this is out of your scope, but do you know by chance whether this is possible?

Thank you,
Roland

**Comment by anshulsharmas** [comment]
Hi Roland,

Great to hear your progress. I don’t believe managed Grafana or Grafana cloud supports <5s refresh. You might want to spin a VM via Azure marketplace & modify the settings, alternatively you can run it locally in a container. 

https://azuremarketplace.microsoft.com/en-in/marketplace/apps/grafana-labs.grafana_oss?tab=overview

**Comment by anshulsharmas** [comment]
Hi Roland,

Great to hear your progress. I don’t believe managed Grafana or Grafana
cloud supports <5s refresh. You might want to spin a VM via Azure
marketplace & modify the setting, alternatively you can run it locally in a
container.

https://azuremarketplace.microsoft.com/en-in/marketplace/apps/grafana-labs.grafana_oss?tab=overview

thanks!
